### ISSUE TITLE
bug with french and special characters

### ISSUE THREAD

**Issue by x0rld** [shvchk/fallout-grub-theme#4] opened 2020-03-07 22:50 UTC
There is a � when the script try to print a special character in french
![image](https://user-images.githubusercontent.com/45242856/76153589-47104700-60ce-11ea-9610-3551a6b71988.png)

**Comment by shvchk** [comment] 2020-03-13 15:25
This might be an issue with your terminal character encoding.

If that's the case, you would have the same problem when using `wget` directly. To check, try `wget -O /dev/null github.com`, I get something like this:

```
> wget -O /dev/null github.com 
URL transformed to HTTPS due to an HSTS policy
--2020-03-13 16:22:33--  https://github.com/
Resolving github.com (github.com)... 140.82.118.3
Connecting to github.com (github.com)|140.82.118.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘/dev/null’

/dev/null                                                             [ <=>                                                                                                                                                          ] 132,25K  --.-KB/s    in 0,1s    

2020-03-13 16:22:34 (1,15 MB/s) - ‘/dev/null’ saved [135423]
```

Also, output of `locale` might be useful.

**Comment by x0rld** [comment] 2020-03-15 13:30
```
wget -O /dev/null github.com 
URL transformed to HTTPS due to an HSTS policy
--2020-03-15 14:29:52--  https://github.com/
Résolution de github.com (github.com)… 140.82.118.3
Connexion à github.com (github.com)|140.82.118.3|:443… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : non indiqué [text/html]
Enregistre : «/dev/null»

/dev/null               [ <=>                ] 132,25K  --.-KB/s    ds 0,07s   

2020-03-15 14:29:52 (1,94 MB/s) - «/dev/null» enregistré [135424]
``` 
the locale
```
LANG=fr_FR.UTF-8
LANGUAGE=
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```

**Comment by shvchk** [comment] 2020-03-25 13:29
Installed Lubuntu in French in a VM, tested in 3 terminal apps (QTerminal, Konsole, GNOME Terminal) with Hack font and can't reproduce your issue. It also could be that you use some font which doesn't support some characters.

Closing for now, let me know if you think it's theme / install script fault.

**Closed by shvchk** 2020-03-25 13:29 UTC

**Comment by freedge** [comment] 2021-11-01 06:20
yeah it's install script fault that sets ```LANG=French``` messing up with the locale

```
# LANG=French grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
Cr�ation du fichier de configuration GRUB...
Th�me trouv�: /boot/grub2/themes/fallout-grub-theme/theme.txt
Ajout de l'entr�e du menu d'amor�age pour les param�tres du firmware UEFI ...
fait
```

**Comment by shvchk** [comment] 2021-11-01 22:54
Thanks, @x0rld and @freedge ! I've changed variables to less generic ones to avoid possible name conflicts.

**Comment by freedge** [comment] 2021-11-02 06:46
thanks for the awesome theme :)
